export const CATEGORY_MIME_MAP: Record<string, string[]> = {
  Images: [
    "image/jpeg",
    "image/png",
    "image/gif",
    "image/webp",
    "image/bmp",
    "image/tiff",
    "image/x-icon",
    "image/vnd.microsoft.icon",
    "image/svg+xml",
    "image/heic",
    "image/heif",
  ],
  Videos: [
    "video/mp4",
    "video/x-matroska",
    "video/webm",
    "video/quicktime",
    "video/x-msvideo",
    "video/x-flv",
    "video/3gpp",
    "video/3gpp2",
    "video/mpeg",
    "video/ogg",
  ],
  Audio: [
    "audio/mpeg",
    "audio/wav",
    "audio/ogg",
    "audio/mp4",
    "audio/webm",
    "audio/x-ms-wma",
    "audio/x-aac",
    "audio/x-flac",
    "audio/x-m4a",
    "audio/3gpp",
    "audio/amr",
  ],
  Documents: [
    "application/pdf",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.oasis.opendocument.text",
    "application/vnd.oasis.opendocument.spreadsheet",
    "application/vnd.oasis.opendocument.presentation",
    "application/x-iwork-pages-sffpages",
    "application/x-iwork-numbers-sffnumbers",
    "application/x-iwork-keynote-sffkey",
    "application/rtf",
  ],
  Text: [
    "text/plain",
    "text/html",
    "text/csv",
    "text/markdown",
    "application/json",
    "application/xml",
    "application/x-yaml",
    "application/javascript",
    "application/x-sh",
  ],
  Archives: [
    "application/zip",
    "application/x-tar",
    "application/x-7z-compressed",
    "application/x-rar-compressed",
    "application/gzip",
    "application/x-bzip2",
    "application/x-gtar",
    "application/x-apple-diskimage",
    "application/x-iso9660-image",
  ],
};
